from . import airport_ambulance_table
from . import airport_ambulance_sex
from . import airport_ambulance_transport_reason
from . import airport_ambulance_trauma_classification
from . import airport_ambulance_non_trauma
from . import airport_ambulance_non_trauma_emergency
from . import airport_ambulance_non_trauma_general
from . import airport_ambulance_trauma
from . import airport_ambulance_trauma_general
from . import airport_ambulance_trauma_moi
from . import airport_ambulance_allergy
from . import airport_ambulance_past_history
from . import airport_ambulance_first_aid
from . import airport_ambulance_first_aid_airway
from . import airport_ambulance_first_aid_trauma
from . import airport_ambulance_first_aid_transport
from . import airport_ambulance_first_aid_cpr
from . import airport_ambulance_first_aid_cpr_aed
from . import airport_ambulance_first_aid_drug
from . import airport_ambulance_first_aid_drug_iv
from . import airport_ambulance_first_aid_other
from . import airport_ambulance_drug_record
from . import airport_ambulance_drug_asl_process
from . import airport_ambulance_vital_signs_record
from . import airport_ambulance_attending_crews_record
from . import airport_ambulance_relation_identity
from . import airport_ambulance_receive_fee_situations
from . import airport_ambulance_receive_fee_yes_pay_method
from . import airport_ambulance_receive_fee_no_pay_method